# Generated by Django 4.0.5 on 2022-06-29 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_rename_user_board_board_user_reply_reply_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='board_num',
            new_name='reply_board',
        ),
    ]
