# Generated by Django 4.0.5 on 2022-06-30 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_delete_logindata'),
        ('board', '0004_alter_board_board_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='board_user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='reply_board',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='board.board'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='reply_user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
    ]
