# Generated by Django 4.0.5 on 2022-06-29 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_user_id_alter_user_user_nm_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginData',
        ),
    ]
