# Generated by Django 4.0.5 on 2022-08-02 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='attached_file',
            field=models.FileField(null=True, upload_to='board/%Y-%m-%d/'),
        ),
    ]
