# Generated by Django 4.0.5 on 2022-08-02 01:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_board_attached_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='attached_file',
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_file_name', models.CharField(max_length=260)),
                ('saved_file_name', models.CharField(max_length=280)),
                ('path', models.CharField(max_length=260)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.board')),
            ],
        ),
    ]
