# Generated by Django 4.0.5 on 2022-08-02 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_file_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='attached_file',
            field=models.FileField(null=True, upload_to='board/%Y-%m-%d/'),
        ),
        migrations.AddField(
            model_name='board',
            name='original_file_name',
            field=models.CharField(max_length=260, null=True),
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
