# Generated by Django 4.0.5 on 2022-06-29 06:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_delete_logindata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('board_num', models.BigAutoField(primary_key=True, serialize=False)),
                ('board_title', models.CharField(max_length=50)),
                ('board_content', models.TextField()),
                ('board_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_content', models.TextField()),
                ('reply_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('board_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.board')),
            ],
        ),
    ]
